ALTER TABLE `accounts` MODIFY COLUMN `ownerid` varchar(65) DEFAULT NULL;
ALTER TABLE `accounts` MODIFY COLUMN `app` varchar(65) DEFAULT NULL;
ALTER TABLE `accounts` MODIFY COLUMN `owner` varchar(49) DEFAULT NULL;
ALTER TABLE `accounts` MODIFY COLUMN `registrationip` varchar(49) DEFAULT NULL;
ALTER TABLE `accounts` MODIFY COLUMN `lastip` varchar(49) DEFAULT NULL;
ALTER TABLE `accounts` MODIFY COLUMN `googleAuthCode` varchar(59) DEFAULT NULL;
ALTER TABLE `apps` MODIFY COLUMN `download` varchar(120) DEFAULT NULL;
ALTER TABLE `apps` ADD `webdownload` varchar(120) DEFAULT NULL;
ALTER TABLE `apps` MODIFY COLUMN `hash` varchar(2000) DEFAULT NULL;
ALTER TABLE `apps` MODIFY COLUMN `webhook` varchar(130) DEFAULT NULL;
ALTER TABLE `apps` MODIFY COLUMN `resellerstore` varchar(69) DEFAULT NULL;
ALTER TABLE `apps` MODIFY COLUMN `nosublevel` varchar(100) DEFAULT 'There is no subscription created for your key level. Contact application developer.';
ALTER TABLE `keys` MODIFY COLUMN `banned` varchar(99) DEFAULT NULL;
ALTER TABLE `chats` ADD PRIMARY KEY (`name`,`app`);
ALTER TABLE `users` ADD UNIQUE KEY `username` (`username`,`app`);
ALTER TABLE `buttons` ADD UNIQUE KEY `value` (`value`,`app`);